[2022-06-20 08:23:18,743] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:23:17.480584+00:00 [queued]>
[2022-06-20 08:23:18,757] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:23:17.480584+00:00 [queued]>
[2022-06-20 08:23:18,758] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 08:23:18,758] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 08:23:18,759] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 08:23:18,778] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_this> on 2022-06-20 08:23:17.480584+00:00
[2022-06-20 08:23:18,783] {standard_task_runner.py:52} INFO - Started process 311 to run task
[2022-06-20 08:23:18,788] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'scenario_insert_only', 'run_this', 'manual__2022-06-20T08:23:17.480584+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/scenario_insert_only.py', '--cfg-path', '/tmp/tmpnxlsj2fn', '--error-file', '/tmp/tmpohncs12x']
[2022-06-20 08:23:18,789] {standard_task_runner.py:80} INFO - Job 10: Subtask run_this
[2022-06-20 08:23:18,854] {task_command.py:370} INFO - Running <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:23:17.480584+00:00 [running]> on host d7f065c79af8
[2022-06-20 08:23:18,938] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=scenario_insert_only
AIRFLOW_CTX_TASK_ID=run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T08:23:17.480584+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T08:23:17.480584+00:00
[2022-06-20 08:23:18,940] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-20 08:23:18,941] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/script/transfer_case_insert_only.py']
[2022-06-20 08:23:18,953] {subprocess.py:85} INFO - Output:
[2022-06-20 08:23:19,152] {subprocess.py:92} INFO - =>table transactions in database y successful
[2022-06-20 08:23:19,154] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-06-20 08:23:19,155] {subprocess.py:92} INFO -   File "/opt/***/dags/script/transfer_case_insert_only.py", line 16, in <module>
[2022-06-20 08:23:19,156] {subprocess.py:92} INFO -     transfer_data_by_last_id()
[2022-06-20 08:23:19,157] {subprocess.py:92} INFO -   File "/opt/***/dags/script/transfer_case_insert_only.py", line 8, in transfer_data_by_last_id
[2022-06-20 08:23:19,157] {subprocess.py:92} INFO -     print("database Y last id: ", db_y_last_id[0])
[2022-06-20 08:23:19,158] {subprocess.py:92} INFO - TypeError: 'int' object is not subscriptable
[2022-06-20 08:23:19,164] {subprocess.py:96} INFO - Command exited with return code 1
[2022-06-20 08:23:19,181] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-20 08:23:19,186] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scenario_insert_only, task_id=run_this, execution_date=20220620T082317, start_date=20220620T082318, end_date=20220620T082319
[2022-06-20 08:23:19,202] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task run_this (Bash command failed. The command returned a non-zero exit code 1.; 311)
[2022-06-20 08:23:19,245] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 08:23:19,297] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
