[2022-06-20 08:29:04,403] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:29:03.619936+00:00 [queued]>
[2022-06-20 08:29:04,424] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:29:03.619936+00:00 [queued]>
[2022-06-20 08:29:04,425] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 08:29:04,426] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 08:29:04,427] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 08:29:04,454] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_this> on 2022-06-20 08:29:03.619936+00:00
[2022-06-20 08:29:04,462] {standard_task_runner.py:52} INFO - Started process 590 to run task
[2022-06-20 08:29:04,466] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'scenario_insert_only', 'run_this', 'manual__2022-06-20T08:29:03.619936+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/scenario_insert_only.py', '--cfg-path', '/tmp/tmplpyrtkko', '--error-file', '/tmp/tmpn393z6ke']
[2022-06-20 08:29:04,468] {standard_task_runner.py:80} INFO - Job 14: Subtask run_this
[2022-06-20 08:29:04,548] {task_command.py:370} INFO - Running <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:29:03.619936+00:00 [running]> on host d7f065c79af8
[2022-06-20 08:29:04,640] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=scenario_insert_only
AIRFLOW_CTX_TASK_ID=run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T08:29:03.619936+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T08:29:03.619936+00:00
[2022-06-20 08:29:04,642] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-20 08:29:04,644] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/script/transfer_case_insert_only.py']
[2022-06-20 08:29:04,658] {subprocess.py:85} INFO - Output:
[2022-06-20 08:29:04,952] {subprocess.py:92} INFO - =>table transactions in database y successful
[2022-06-20 08:29:04,954] {subprocess.py:92} INFO - ========= 0
[2022-06-20 08:29:04,956] {subprocess.py:92} INFO - database X:
[2022-06-20 08:29:04,957] {subprocess.py:92} INFO - column "none" does not exist
[2022-06-20 08:29:04,959] {subprocess.py:92} INFO - LINE 1: ...ion_date, sale_value FROM transactions WHERE id > None ORDER...
[2022-06-20 08:29:04,960] {subprocess.py:92} INFO -                                                              ^
[2022-06-20 08:29:04,963] {subprocess.py:92} INFO - 
[2022-06-20 08:29:04,964] {subprocess.py:92} INFO - []
[2022-06-20 08:29:04,966] {subprocess.py:92} INFO - insert list transaction successful
[2022-06-20 08:29:04,968] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-20 08:29:05,021] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=scenario_insert_only, task_id=run_this, execution_date=20220620T082903, start_date=20220620T082904, end_date=20220620T082905
[2022-06-20 08:29:05,087] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-20 08:29:05,137] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
