[2022-06-20 08:27:36,966] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:27:35.936911+00:00 [queued]>
[2022-06-20 08:27:36,981] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:27:35.936911+00:00 [queued]>
[2022-06-20 08:27:36,983] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 08:27:36,984] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 08:27:36,985] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 08:27:37,007] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_this> on 2022-06-20 08:27:35.936911+00:00
[2022-06-20 08:27:37,012] {standard_task_runner.py:52} INFO - Started process 520 to run task
[2022-06-20 08:27:37,017] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'scenario_insert_only', 'run_this', 'manual__2022-06-20T08:27:35.936911+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/scenario_insert_only.py', '--cfg-path', '/tmp/tmpm44dy8_3', '--error-file', '/tmp/tmpqjy1eryj']
[2022-06-20 08:27:37,019] {standard_task_runner.py:80} INFO - Job 12: Subtask run_this
[2022-06-20 08:27:37,113] {task_command.py:370} INFO - Running <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:27:35.936911+00:00 [running]> on host d7f065c79af8
[2022-06-20 08:27:37,209] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=scenario_insert_only
AIRFLOW_CTX_TASK_ID=run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T08:27:35.936911+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T08:27:35.936911+00:00
[2022-06-20 08:27:37,211] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-20 08:27:37,213] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/script/transfer_case_insert_only.py']
[2022-06-20 08:27:37,225] {subprocess.py:85} INFO - Output:
[2022-06-20 08:27:37,520] {subprocess.py:92} INFO - =>table transactions in database y successful
[2022-06-20 08:27:37,522] {subprocess.py:92} INFO - database X:
[2022-06-20 08:27:37,523] {subprocess.py:92} INFO - column "none" does not exist
[2022-06-20 08:27:37,524] {subprocess.py:92} INFO - LINE 1: ...ion_date, sale_value FROM transactions WHERE id > None ORDER...
[2022-06-20 08:27:37,525] {subprocess.py:92} INFO -                                                              ^
[2022-06-20 08:27:37,526] {subprocess.py:92} INFO - 
[2022-06-20 08:27:37,528] {subprocess.py:92} INFO - []
[2022-06-20 08:27:37,529] {subprocess.py:92} INFO - insert list transaction successful
[2022-06-20 08:27:37,539] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-20 08:27:37,588] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=scenario_insert_only, task_id=run_this, execution_date=20220620T082735, start_date=20220620T082736, end_date=20220620T082737
[2022-06-20 08:27:37,637] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-20 08:27:37,683] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
